on: 
  push:
    branches:
    - dev
    paths-ignore:
      - 'Documentation/**'
      - '**.md'
name: 持续交付(CD)
jobs:
  buildDevDocker:
    name: 构建并提交Docker镜像(Dev)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 设置 QEMU
      uses: docker/setup-qemu-action@v3
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: actions/cache@v4
      with: 
        path: /tmp/buildxcache
        key: ${{ runner.os }}-docker-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-buildx-
    - name: 登录 Docker
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
    - name: 构建并推送 PicaBridge Docker镜像(Dev)
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --tag yareiy/picabridge:dev \
          --cache-from "type=local,src=/tmp/buildxcache" \
          --cache-to "type=local,dest=/tmp/buildxcache" \
          --file ./Dockerfile .
