on: 
  release:
    types: [published]
name: 发布新版本
jobs:

  buildLatestDocker:
    name: 构建最新 Docker 镜像
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 设置 QEMU
      uses: docker/setup-qemu-action@v3
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: actions/cache@v4
      with: 
        path: /tmp/buildxcache
        key: ${{ runner.os }}-docker-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-buildx-
    - name: 登录 Docker
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
    - name: 构建/推送最新Docker镜像并用版本号标记
      run: |
        TAG=${GITHUB_REF:10:10}
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --tag yareiy/picabridge:latest \
          --tag yareiy/picabridge:$TAG \
          --cache-from "type=local,src=/tmp/buildxcache" \
          --cache-to "type=local,dest=/tmp/buildxcache" \
          --file ./Dockerfile .
